### ISSUE TITLE
Listening to a song while uploading will stop when upload complete

### ISSUE THREAD

**Issue by angrykoala** [mpvillafranca/hearcloud#25]
Why can't I listen to the songs after they are uploaded in the same screen?

**Comment by mpvillafranca** [comment]
Because the preview that the uploader offers to you it's different than the hearcloud player. Maybe would be better not showing that preview (which is playing your local file) and just add a play button together to the uploaded file to play it with the hearcloud player (which is already on the server and loaded by an url)...

**Comment by angrykoala** [comment]
Use the same page until user wants to change so the music don't stop
